In [1]:
from pdb_parser import parse
from shrake_rupley import calculate_surface_area, parse_results_by_residue

In [2]:
atoms = parse("1ubq")
print("Number of atoms in PDB file: {:,}".format(len(atoms)))

Number of atoms in PDB file: 602

In [3]:
results = calculate_surface_area(atoms)
parsed_results = parse_results_by_residue(results)
print("Total surface area: {:.2f} A^2".format(sum(parsed_results.area)))

Total surface area: 4873.98 A^2

In [4]:
parsed_results

   chainid resid resname        area
0        A     1     MET   59.380290
1        A     2     GLN   74.106401
2        A     3     ILE    0.000000
3        A     4     PHE   55.029812
4        A     5     VAL    0.000000
5        A     6     LYS  102.878363
6        A     7     THR   20.059279
7        A     8     LEU  141.910348
8        A     9     THR  129.109405
9        A    10     GLY   68.327546
10       A    11     LYS  105.832298
11       A    12     THR   63.378909
12       A    13     ILE    5.810690
13       A    14     THR   64.529989
14       A    15     LEU    7.747586
15       A    16     GLU  137.980425
16       A    17     VAL    6.467492
17       A    18     GLU  100.884499
18       A    19     PRO   53.264656
19       A    20     SER   83.098896
20       A    21     ASP   34.398345
21       A    22     THR   51.394780
22       A    23     ILE    0.000000
23       A    24     GLU  118.157394
24       A    25     ASN   50.884586
25       A    26     VAL    0.000000
26       A    27     LYS   18.141650
27       A    28     ALA   47.175831
28       A    29     LYS   70.041599
29       A    30     ILE    0.000000
..     ...   ...     ...         ...
46       A    47     GLY   75.364713
47       A    48     LYS  104.689596
48       A    49     GLN  107.239731
49       A    50     LEU    6.568023
50       A    51     GLU  119.485241
51       A    52     ASP   61.839948
52       A    53     GLY   49.720940
53       A    54     ARG  118.618999
54       A    55     THR   34.897649
55       A    56     LEU    0.000000
56       A    57     SER   65.355180
57       A    58     ASP   84.473657
58       A    59     TYR   37.901849
59       A    60     ASN  116.452556
60       A    61     ILE    3.940814
61       A    62     GLN  124.806680
62       A    63     LYS  136.237050
63       A    64     GLU   97.897054
64       A    65     SER   22.063196
65       A    66     THR   53.498391
66       A    67     LEU    0.000000
67       A    68     HIS   72.697292
68       A    69     LEU    1.313605
69       A    70     VAL   40.674828
70       A    71     LEU   76.233468
71       A    72     ARG  118.959966
72       A    73     LEU  124.026727
73       A    74     ARG  209.158861
74       A    75     GLY   79.065091
75       A    76     GLY  149.778571

[76 rows x 4 columns]

In [ ]:
# end of notebook